apiVersion: v1
kind: Pod
metadata:
  name: your-pod-name
spec:
  containers:
  - name: your-container-name
    image: your-image-name:tag
    ports:
    - containerPort: 80  # Port number for your container
